name: FlutterGalleryApp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cached_network_image: ^2.2.0
  connectivity: ^2.0.0
  gallery_saver: ^2.0.1
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  mobx_codegen: ^1.1.2
  provider: ^4.3.3
  json_annotation: ^3.1.1
  webview_flutter: ^1.0.7
  flutter_secure_storage: ^3.3.5
  fluro: ^1.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1

flutter:
  uses-material-design: true
  fonts:
  - family:  AppIcons
    fonts:
      - asset: assets/fonts/AppIcons.ttf